// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAno1rplkC0aBcD5vFsLcuq1QPdJfxL3HY',
    appId: '1:835821485602:web:abb2d1aa2e4fe04d24947b',
    messagingSenderId: '835821485602',
    projectId: 'chatapp-7d30d',
    authDomain: 'chatapp-7d30d.firebaseapp.com',
    storageBucket: 'chatapp-7d30d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCny2jm9WsQ7CzkmKJC0uMOn-ejWvOc_Ao',
    appId: '1:835821485602:android:e11b56e05464cbac24947b',
    messagingSenderId: '835821485602',
    projectId: 'chatapp-7d30d',
    storageBucket: 'chatapp-7d30d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnis5Dfv8FyaG7BgKCIpAG7jC006SNOI',
    appId: '1:835821485602:ios:c37420681f52e25124947b',
    messagingSenderId: '835821485602',
    projectId: 'chatapp-7d30d',
    storageBucket: 'chatapp-7d30d.appspot.com',
    iosBundleId: 'com.example.eduflex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwnis5Dfv8FyaG7BgKCIpAG7jC006SNOI',
    appId: '1:835821485602:ios:2bd0e8b795c494cb24947b',
    messagingSenderId: '835821485602',
    projectId: 'chatapp-7d30d',
    storageBucket: 'chatapp-7d30d.appspot.com',
    iosBundleId: 'com.example.eduflex.RunnerTests',
  );
}
